version: '3.8'

services:
  mysql:
    image: mysql/mysql-server
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: StudentLog
      MYSQL_USER: root
      MYSQL_PASSWORD: Helloworld@123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d  # Mount the init directory
    ports:
      - "3307:3306"

  myapp:
    image: jdbcwebapp.war:latest  # Replace with your actual web app image
    container_name: myapp_container
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: StudentLog
      DB_USER: root
      DB_PASSWORD: Helloworld@123 
    depends_on:
      - mysql
    ports:
      - "9090:8080"  # Change this to your app's port

volumes:
  mysql_data:
